---
title: "学术笔记"
layout: collection
permalink: /notes/
collection: notes
entries_layout: grid
classes: wide
---

{% if site.notes.size > 0 %}
  {% assign sorted_notes = site.notes | sort: 'date' | reverse %}
  
  <div class="entries-{{ entries_layout }}">
    {% for post in sorted_notes %}
      {% include archive-single.html type=entries_layout %}
    {% endfor %}
  </div>
{% else %}
  <p>暂无学术笔记内容，敬请期待...</p>
{% endif %}

---

## 📚 关于学术笔记

这里收录了我的数学研究笔记和理论探索文档，涵盖：

- **理论数学**：代数、分析、几何等核心领域
- **应用数学**：计算方法、数值分析、优化理论
- **跨学科研究**：数学在其他领域的应用
- **学习总结**：重要数学概念的深度理解

每篇笔记都包含详细的数学推导和个人思考，希望能为同行研究者提供参考。
