# ============================================================================
# GitHub Pages 兼容配置
# ============================================================================

# 网站基本信息
title: "Deep Matrix Research"
subtitle: "Mathematical Insights & Computational Explorations"
description: "个人数学研究笔记与理论探索 | Mathematical Research & Theoretical Analysis"
author: "Linyi"
email: "lin@deep-matrix.org"

# 网站设置
url: "https://z-athena.org"
baseurl: ""
repository: "linyi1225/linyi1225.github.io"

# 主题配置 - 使用远程主题
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "contrast"

# 必须在 plugins 之前声明
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Markdown配置 - 数学公式支持优化
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: rouge
  math_engine: mathjax
  math_engine_opts:
    preview: true
    preview_as_code: false

# 分页设置
paginate: 5
paginate_path: /page:num/

# 集合配置 - 支持层次化目录结构
collections:
  notes:
    output: true
    permalink: /:collection/:path/
    title: "学术笔记"
  code:
    output: true
    permalink: /:collection/:path/
    title: "代码实现"

# 作者信息
author:
  name: "Linyi"
  avatar: "/assets/images/avatar.jpg"
  bio: "数学研究者 | 理论探索 | 计算数学"
  location: "中国"
  email: "lin@deep-matrix.org"
  links:
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0009-0009-6464-2663"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/linyi1225"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:lin@deep-matrix.org"

# 默认设置 - 针对层次化目录优化
defaults:
  # 学术笔记默认设置
  - scope:
      path: "_notes"
      type: notes
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      toc: true
      toc_label: "目录"
      toc_icon: "cog"
      mathjax: true
  # 数值分析系列特定设置
  - scope:
      path: "_notes/numerical-analysis"
      type: notes
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      toc: true
      toc_label: "目录"
      toc_icon: "cog"
      mathjax: true
      classes: wide
      sidebar:
        nav: "numerical-analysis"
  # 概率论系列特定设置
  - scope:
      path: "_notes/probability-theory"
      type: notes
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      toc: true
      toc_label: "目录"
      toc_icon: "cog"
      mathjax: true
      classes: wide
      sidebar:
        nav: "probability-theory"
  # 代码实现默认设置
  - scope:
      path: "_code"
      type: code
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      classes: wide
  # 博客文章默认设置
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      show_date: true
  # 页面默认设置
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# 搜索功能
search: true
search_full_content: true
search_provider: lunr

# 社交设置
social:
  type: Person
  name: Linyi
  links:
    - "https://github.com/linyi1225"
    - "https://orcid.org/0009-0009-6464-2663"

# SEO优化
locale: "zh-CN"
title_separator: "-"
og_image: "/assets/images/site-logo.png"

# 数学公式支持 - MathJax配置
mathjax:
  enable: true
  combo: "tex-mml-chtml"
  tags: "ams"

# 头部脚本 - MathJax支持
head_scripts:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# 相关文章
related: true

# 压缩HTML
compress_html:
  clippings: all
  ignore:
    envs: development

# 分析和统计
analytics:
  provider: false  # 如需要可设置为 "google" 等

# 评论系统
comments:
  provider: false  # 如需要可设置评论系统

# 网站验证
# google_site_verification: "your-verification-code"

# 导航配置 - 支持侧边栏导航
navigation:
  numerical-analysis:
    - title: "理论基础"
      children:
        - title: "实数理论"
          url: /notes/numerical-analysis/foundations/01-real-numbers/
        - title: "序列理论"
          url: /notes/numerical-analysis/foundations/02-sequences/
        - title: "完备性理论"
          url: /notes/numerical-analysis/foundations/03-completeness/
    - title: "分析理论"
      children:
        - title: "函数概念"
          url: /notes/numerical-analysis/analysis/01-functions/
        - title: "极限理论"
          url: /notes/numerical-analysis/analysis/02-limits/
        - title: "连续性"
          url: /notes/numerical-analysis/analysis/03-continuity/
        - title: "导数理论"
          url: /notes/numerical-analysis/analysis/04-derivatives/
    - title: "误差理论"
      children:
        - title: "误差分类"
          url: /notes/numerical-analysis/errors/01-error-types/
        - title: "收敛理论"
          url: /notes/numerical-analysis/errors/02-convergence/
        - title: "数值稳定性"
          url: /notes/numerical-analysis/errors/03-stability/
    - title: "空间理论"
      children:
        - title: "线性空间"
          url: /notes/numerical-analysis/spaces/01-linear-spaces/
        - title: "内积空间"
          url: /notes/numerical-analysis/spaces/02-inner-product/
        - title: "赋范空间"
          url: /notes/numerical-analysis/spaces/03-normed-spaces/
        - title: "逼近论"
          url: /notes/numerical-analysis/spaces/04-approximation/
    - title: "应用理论"
      children:
        - title: "迭代法理论"
          url: /notes/numerical-analysis/applications/01-iteration/
        - title: "泛函分析"
          url: /notes/numerical-analysis/applications/02-functional-analysis/
        - title: "未来发展"
          url: /notes/numerical-analysis/applications/03-future-directions/

  probability-theory:
    - title: "测度理论"
      children:
        - title: "测度空间"
          url: /notes/probability-theory/measure/01-measure-spaces/
        - title: "可测函数"
          url: /notes/probability-theory/measure/02-measurable-functions/
    - title: "概率理论"
      children:
        - title: "概率空间"
          url: /notes/probability-theory/probability/01-probability-spaces/
        - title: "随机变量"
          url: /notes/probability-theory/probability/02-random-variables/

# 排除文件和目录
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
  - .gitignore
  - .git/
  - Makefile
  - package.json
  - package-lock.json

# 包含文件
include:
  - _pages
  - .htaccess

# Sass配置
sass:
  sass_dir: _sass
  style: compressed

# 时区设置
timezone: Asia/Shanghai

# 编码
encoding: utf-8

# 生成设置
future: false
unpublished: false
safe: true
incremental: false
profile: false
strict_front_matter: false
