# 网站基本信息
title: "学术研究托管"
subtitle: "Mathematical Research Notes"
description: "个人学术研究与理论探索"
author: "你的姓名"
email: "lin@deep-matrix.org"

# 网站设置
url: "https://z-athena.org"
baseurl: ""
repository: "linyi1225.github.io"

# 主题配置 - 简洁学术风格
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# 数学公式支持
markdown: kramdown
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# MathJax配置 - 完整数学支持
mathjax:
  enable: true
  combo: "tex-mml-chtml"
  tags: "ams"

# 插件
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-archives

# 动态内容集合 - 不预设具体领域
collections:
  notes:
    output: true
    permalink: /:collection/:name/
  code:
    output: true
    permalink: /:collection/:name/

# 标签和分类归档
jekyll-archives:
  enabled:
    - tags
    - categories
  layout: archive-taxonomy
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

# 导航菜单 - 保持通用
main:
  - title: "首页"
    url: /
  - title: "学术笔记"
    url: /notes/
  - title: "代码实现"
    url: /code/
  - title: "标签索引"
    url: /tags/
  - title: "关于"
    url: /about/

# 作者信息
author:
  name: "Linyi"
  avatar: "/assets/images/avatar.jpg"
  bio: "数学研究者"
  location: "中国"
  email: ""
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Linyi1225/linyi1225.github.io"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/your-orcid"

# 默认设置
defaults:
  # 学术笔记
  - scope:
      path: "_notes"
      type: notes
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      sidebar:
        nav: "dynamic"
  # 代码文档
  - scope:
      path: "_code"
      type: code
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # 普通页面
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# 相关文章设置
related: true
